### PR TITLE
Update oneMKL interface

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
`oneMKL` has an implementation of `axpby!`. I missed it (https://oneapi-src.github.io/oneMKL/domains/blas/axpby.html).

**Comment by maleadt** [comment]
> Update: It seems that axpby is not available on GPUs.

Those wrappers are ours, https://github.com/JuliaGPU/oneAPI.jl/blob/07e5565cf49d4158b106d043ea8f36994a01e1d2/deps/src/onemkl.cpp#L559-L587, so you can just copy-paste that code (and their corresponding definitions in the headers).

**Comment by amontoison** [comment]
@maleadt 
I updated `onemkl.cpp` and `onemkl.h` but I can't call `onemklXaxpby`.
I probably need to regenerate something, right?

**Comment by maleadt** [comment]
Yes, run `deps/build_cmt.jl`. On CI this should happen automatically.

**Comment by amontoison** [comment]
Tim, I don't why but it's not working. I regenerate the shared library with `build_local.jl`, I see the symbols of the new routines with `nm -D` command.

**Comment by maleadt** [comment]
Are you running with `--project`? The build script generates a LocalPreferences.toml that should get picked up by the JLL. You can confirm by inspecting the path of the library that's loaded, `oneAPI.Support.liboneapi_support`, which should point to somewhere in your scratch space (as opposed to an artifact path).

**Comment by amontoison** [comment]
I forgot to regenerate `lib/support/liboneapi_support.jl` with `res/wrap.jl`.

I don't know if you have an automatic process for updating `res/support.toml`.
I modified the file myself.

**Comment by maleadt** [comment]
> I don't know if you have an automatic process for updating `res/support.toml`.

No, that one is hand-edited, so that the generated headers aren't.

**Comment by maleadt** [comment]
I already tagged a release that fixes the quirk. This should go in 1.1. Do you  need the functionality? If so, I'd release 1.1 sooner rather than later.

**Comment by amontoison** [comment]
I just needed a release that fixes the quirk so that's fine.
I can wait the release 1.1 for the optimized `axpby!` and `reflect!`.

**Pull request merged**
