### PR TITLE
oneMKL: Support for iamax and iamin

### PR DESCRIPTION
**Pull request by Sarbojit2019**

### CODE REVIEW

**Comment by maleadt** [comment]
Please rebase on top of master, that should fix the CI issues.

**Comment by maleadt** [comment]
Looks like it picked up the wrong library. I'll take a look.

**Comment by Sarbojit2019** [comment]
@maleadt, it is now failing for julia1.7. I could not findout anything related can you please take a loo?.

**Comment by maleadt** [comment]
Looks like an unrelated error. I've restarted the tests. For future reference, you can always re-start the tests by force-pushing, or closing and re-opening the pull request.

**Comment by Sarbojit2019** [comment]
Great, looks like all clean now. Let me know if it is ready to get merged.

**Pull request merged**
