### PR TITLE
Test Float64 emulation.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
```
      From worker 9:	ERROR: Out-of-bounds array access.
      From worker 14:
      From worker 14:	signal (11): Segmentation fault
      From worker 14:	in expression starting at none:1
      From worker 9:	ERROR: Out-of-bounds array access.
      From worker 9:	ERROR: Out-of-bounds array access.
      From worker 9:	ERROR: Out-of-bounds array access.
      From worker 9:	Abort was called at 84 line in file:
      From worker 9:	/workspace/srcdir/compute-runtime/level_zero/core/source/cmdlist/cmdlist.cpp
      From worker 9:
      From worker 9:	signal (6): Aborted
      From worker 9:	in expression starting at none:1
      From worker 9:	gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
      From worker 9:	abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
      From worker 9:	_ZN3NEO14abortExecutionEv at /home/tim/Julia/depot/artifacts/25280ba59a3ef0bdfd442ed62f0ec52a2f13a79f/lib/libze_intel_gpu.so.1 (unknown line)
      From worker 9:	_ZN3NEO18abortUnrecoverableEiPKc at /home/tim/Julia/depot/artifacts/25280ba59a3ef0bdfd442ed62f0ec52a2f13a79f/lib/libze_intel_gpu.so.1 (unknown line)
      From worker 9:	_ZN2L011CommandList15getHostPtrAllocEPKvmb at /home/tim/Julia/depot/artifacts/25280ba59a3ef0bdfd442ed62f0ec52a2f13a79f/lib/libze_intel_gpu.so.1 (unknown line)
      From worker 9:	_ZN2L021CommandListCoreFamilyIL14GFXCORE_FAMILY18EE20getAlignedAllocationEPNS_6DeviceEPKvmb at /home/tim/Julia/depot/artifacts/25280ba59a3ef0bdfd442ed62f0ec52a2f13a79f/lib/libze_intel_gpu.so.1 (unknown line)
      From worker 9:	_ZN2L021CommandListCoreFamilyIL14GFXCORE_FAMILY18EE16appendMemoryCopyEPvPKvmP18_ze_event_handle_tjPS7_ at /home/tim/Julia/depot/artifacts/25280ba59a3ef0bdfd442ed62f0ec52a2f13a79f/lib/libze_intel_gpu.so.1 (unknown line)
      From worker 9:	macro expansion at /home/tim/Julia/pkg/oneAPI/lib/level-zero/libze.jl:1435 [inlined]
      From worker 9:	macro expansion at /home/tim/Julia/pkg/oneAPI/lib/level-zero/utils.jl:5 [inlined]
      From worker 9:	macro expansion at /home/tim/Julia/pkg/oneAPI/lib/level-zero/oneL0.jl:21 [inlined]
      From worker 9:	zeCommandListAppendMemoryCopy at /home/tim/Julia/pkg/oneAPI/lib/utils/call.jl:24
      From worker 9:	append_copy! at /home/tim/Julia/pkg/oneAPI/lib/level-zero/copy.jl:7 [inlined]
      From worker 9:	append_copy! at /home/tim/Julia/pkg/oneAPI/lib/level-zero/copy.jl:7 [inlined]
```

Interesting; either this is a compiler bug, or we're actually doing an OOB array copy.

**Comment by maleadt** [comment]
Should probably start with upgrading our binary toolchain; it's been a while.

**Comment by maleadt** [comment]
Still has the OOB accesses.

**Comment by maleadt** [comment]
Running some of the problematic tests in isolation causes GPU hangs:

```julia
range = Float64(1):Float64(10)
for (sz,dims) in [(10,)=>[1], (10,10)=>[1,2], (10,10,10)=>[1,2,3], (10,10,10)=>[],
                    (10,)=>:, (10,10)=>:, (10,10,10)=>:,
                    (10,10,10)=>[1], (10,10,10)=>[2], (10,10,10)=>[3],
                    (0,)=>[1]]
    sum(oneArray(rand(range, sz)))
    sum(abs, oneArray(rand(range, sz)))
    Array(sum(oneArray(rand(range, sz)); dims=dims))
    prod(oneArray(rand(range, sz)))
    prod(abs, oneArray(rand(range, sz)))
    Array(prod(oneArray(rand(range, sz)); dims=dims))
end
```

```
[Fri Jan 20 08:30:44 2023] i915 0000:00:02.0: [drm] GPU HANG: ecode 12:1:85dcfffb, in julia [3760530]
[Fri Jan 20 08:30:44 2023] i915 0000:00:02.0: [drm] Resetting rcs0 for stopped heartbeat on rcs0
[Fri Jan 20 08:30:44 2023] i915 0000:00:02.0: [drm] julia[3760530] context reset due to GPU hang
```

**Comment by pengtu** [comment]
Just a comment: it is unlikely that the GPU driver team will fix any FP64 emulation errors.

**Comment by maleadt** [comment]
Good to know, thanks. I'll also remove the mention from our README then.

**Pull request closed without merging**
