### PR TITLE
Blas iamax and iamin support

### PR DESCRIPTION
**Pull request by Sarbojit2019**

### CODE REVIEW

**Comment by maleadt** [comment]
This does still seem to segfault?

Also needs a rebase.

**Comment by Sarbojit2019** [comment]
> This does still seem to segfault?
> 
> Also needs a rebase.

On my setup it does not crash. Does it crash on your setup?
Rebase I will do. Any other suggestions please let me know.

**Comment by pengtu** [comment]
@maleadt, @Sarbojit2019:

Based on our discussion, I have experimented with an alternative approach
 
[](https://github.com/pengtu/oneAPI.jl/commit/7fc47b5a39222b697ff7b156ee9a84c846d70181)

There, we just allocate an oneArray variable in the Julia wrappers.jl and pass it to the oneMKL function to receive the result (using sycl::buffer version of the iamax/iamin function).  I like it better since we don't need to pass the context and device into the oneMKL C wrapper and we keep all the data copying inside Julia.

Please comment so we can settle on a common schema for this kind of patterns going forward.

**Comment by maleadt** [comment]
Yeah, that seems like a better approach, and will make it easier to switch to a direct C++ wrapper once/if we get proper C++ FFI. You could probably go all the way and perform the `wait` in Julia too (which has other advantages, e.g., being able to switch to another cooperative task while waiting), but that's not crucial and is easily changed afterwards.

**Comment by pengtu** [comment]
@maleadt Thank you Tim!  We would like to learn how to do the wait in Julia.  Let's go with your suggestion of merging    @Sarbojit2019's new revision and adding waiting in Julia afterward.

**Comment by maleadt** [comment]
> Let's go with your suggestion of merging @Sarbojit2019's new revision and adding waiting in Julia afterward.

You mean your approach? I don't see a push by @Sarbojit2019 here. The current version fails CI, so cannot be merged.

**Comment by Sarbojit2019** [comment]
> > Let's go with your suggestion of merging @Sarbojit2019's new revision and adding waiting in Julia afterward.
> 
> You mean your approach? I don't see a push by @Sarbojit2019 here. The current version fails CI, so cannot be merged.

I have updated PR#235. Once that is merged I will close this one.

**Comment by maleadt** [comment]
Superseded by https://github.com/JuliaGPU/oneAPI.jl/pull/235.

**Pull request closed without merging**
