### PR TITLE
Support half type primitives

### PR DESCRIPTION
**Pull request by kballeda**

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks. Can you update the wrapper generator in `res/wrap.jl` so that these wrappers don't get lost? the `lib` files (like `libonemkl.jl`) aren't really intended to be hand-edited.

**Comment by kballeda** [comment]
> Thanks. Can you update the wrapper generator in `res/wrap.jl` so that these wrappers don't get lost? the `lib` files (like `libonemkl.jl`) aren't really intended to be hand-edited.

@maleadt : Following location needs an update supporting 'H' type (half type). 
https://github.com/JuliaGPU/oneAPI.jl/blob/1c90e6dd6c99d2aa3bbfb6488f025dead5302389/res/wrap.jl#L78

Can you please elaborate on steps to autogenerate libonemkl.jl. Also, when I try running res/wrap.jl it fails to find ./libze_prologue.jl.

**Comment by maleadt** [comment]
> when I try running res/wrap.jl it fails to find ./libze_prologue.jl.

Rebase your PR, I added the missing files

You should just run `julia --project=res res/wrap.jl`

**Comment by kballeda** [comment]
@maleadt  : CI checks are failing for Julia 1.9 - dot primitive, rest of the versions are going through. can you please take a look?

**Comment by kballeda** [comment]
> @maleadt : CI checks are failing for Julia 1.9 - dot primitive, rest of the versions are going through. can you please take a look?

@maleadt : I have provided a fix for Julia 1.9 failure. Please take a look.

**Comment by maleadt** [comment]
LGTM, fixing the ambiguity by using Vector seems like the correct approach: https://github.com/JuliaLang/julia/pull/44758#issuecomment-1405083580

**Review by maleadt — APPROVED** [review]
Thanks for the PR!

**Comment by kballeda** [comment]
@maleadt  Thanks review and looking into it.

**Pull request merged**
