### PR TITLE
Support Blas-Extension Primitives

### PR DESCRIPTION
**Pull request by kballeda**
Following primitives are enabled. 
getrf
geqrf
getri
gels_Batched
dgmm_batched

### CODE REVIEW

**Comment by kballeda** [comment]
@maleadt  I have filed a Git issue on https://github.com/JuliaGPU/oneAPI.jl/issues/357 . This issue is observed as part of our oneAPI.jl CI flow. Can you please take a look ?

**Comment by amontoison** [comment]
@kballeda Can I help on something here? I would like to  interface the additional LAPACK routines `orgqr` and `ormqr`.

**Comment by kballeda** [comment]
> @kballeda Can I help on something here? I would like to interface the additional LAPACK routines `orgqr` and `ormqr`.

Sure Thank you !

**Comment by amontoison** [comment]
@kballeda Did you update the cpp file by hand?
I didn't remember if we used an automatic procedure for BLAS routines.

**Comment by kballeda** [comment]
> @kballeda Did you update the cpp file by hand? I didn't remember if we used an automatic procedure for BLAS routines.

Yes cpp file is updated by hand.

**Comment by kballeda** [comment]
#376 inherits the changes from here.

**Pull request closed without merging**
