### PR TITLE
Upgrade the C interface for oneAPI 2024.1.0

### LINKED ISSUE #401: When should we use __FORCE_MKL_FLUSH__ in the C interface?
I don't understand why I have a segementation fault when I call some C functions that contains `__FORCE_MKL_FLUSH__`:
https://github.com/JuliaGPU/oneAPI.jl/blob/master/deps/src/onemkl.cpp#L11-L12

I don't have anymore a segmentation fault when I remove `__FORCE_MKL_FLUSH__` but it only concerns a few routines (`geqrf` -- LAPACK and `set_csr_data` -- SPARSE).
Why don't we have the same behaviour with all routines?
I use `__FORCE_MKL_FLUSH__` after the routines that return `void`.

```julia
[5119] signal (11.1): Erreur de segmentation
in expression starting at REPL[7]:1
_ZNK4sycl3_V15event11get_backendEv at /home/alexis/.julia/scratchspaces/8f75cd03-7ff8-4ecb-9b8f-daf728133b1b/conda/lib/libsycl.so.7 (unknown line)
_ZN4sycl3_V110get_nativeILNS0_7backendE2ENS0_5eventEEENS0_14backend_traitsIXT_EE11return_typeIT0_EERKS7_ at /home/alexis/.julia/scratchspaces/8f75cd03-7ff8-4ecb-9b8f-daf728133b1b/deps/lib/liboneapi_support.so (unknown line)
onemklSgeqrf at /home/alexis/.julia/scratchspaces/8f75cd03-7ff8-4ecb-9b8f-daf728133b1b/deps/lib/liboneapi_support.so (unknown line)
onemklSgeqrf at /home/alexis/Bureau/git/oneAPI.jl/lib/support/liboneapi_support.jl:2473
unknown function (ip: 0x7fb6b8136699)
```

### PR DESCRIPTION
**Pull request by amontoison**
close #401 

The tests are failing because of an upstream issue:
https://github.com/JuliaGPU/oneAPI.jl/pull/404#issuecomment-2026874806

If we merge this PR and update `oneAPI_Support_jll.jl`, we must bump the version number to `0.4.0`.

### CODE REVIEW

**Comment by amontoison** [comment]
@pengtu 
Do you have a routine in `oneMKL` that returns the version number?
It will help to support different versions of oneMKL in oneAPI.jl.

What should we do for the failing build `Validations`?

**Comment by maleadt** [comment]
> What should we do for the failing build `Validation`?

Reduce to the minimal failing API calls and file upstream. When we've done that, awaiting a fix, selectively disable those tests when running in validation mode.

**Comment by amontoison** [comment]
> > What should we do for the failing build `Validation`?
> 
> Reduce to the minimal failing API calls and file upstream. If you have a Julia MWE I can help reducing to something C++ for reporting purposes, if you want.
> 
> When we've done that, awaiting a fix, selectively disable those tests when running in validation mode.

@maleadt I found the culprit, it's the routine `axpby`. I prepared the following Julia MWE:
```julia
for T in (Float32, Float64, ComplexF32, ComplexF64)
  n = 10
  alpha = rand(T)
  x = rand(T, n) |> oneVector
  beta = rand(T)
  y = rand(T, n) |> oneVector
  axpby!(n, alpha, x, beta, y)
end
```

**Comment by maleadt** [comment]
Good to go?

**Comment by maleadt** [comment]
Filed upstream as https://github.com/oneapi-src/oneMKL/issues/473

**Pull request merged**
